Dockerfile, install.sh
Job: https://github.hpe.com/hpe/ezaf/pull/1713
=> EZAF-2506: script and docker file to provide demo examples in shared folder

Data-Engineering/PrestoDB/readme.md, Data-Science/Ray-CPU/experiment-ray-cpu.ipynb, Data-Science/Ray-GPU/ray_gpu_sample.py
As mentioned I have updated the code here @prasadadireddi, please review and merge into fy23-q3.
=> EZAF-2686 || ray distributed cpu compute check

Data-Science/Ray/Anomaly-Detection-Banking/ray_acceleration_experiment_fraud_detecting_on_banking_system.ipynb, Data-Science/Ray/Anomaly-Detection-Banking/readme.md
As discussed updated readme, notebook.
=> EZAF-2686: runtime_env updated

Data-Science/Feast/definitions.py, Data-Science/Feast/ride-sharing-example.ipynb, install.sh
https://jira-pro.it.hpe.com:8443/browse/EZAF-2729
=> EZAF-2729: updated Feast example

Data-Science/Ray/Ray-Custome-Storage-Path/ray-custom-s3-storage-path.ipynb, Data-Science/Ray/Ray-Custome-Storage-Path/ray-custom-storage-path.ipynb, Data-Science/Ray/Ray-Custome-Storage-Path/readme.md, Data-Science/Ray/Ray-RuntimeEnv-Proxy/ray-cpu-experiment.ipynb, Data-Science/Ray/Ray-RuntimeEnv-Proxy/ray-runtimeenv-workaround.ipynb, Data-Science/Ray/Ray-RuntimeEnv-Proxy/readme.md
@prasadadireddi review the same, I have tested its working. 
cc: @sercanCyberVision
=> EZAF-2419 || ray runtime-env issue hack/ workaround

install.sh
https://jira-pro.it.hpe.com:8443/browse/EZAF-3013
additionally: https://github.hpe.com/hpe/ezaf/pull/1933
=> EZAF-3013:  Update image tag to q4

Data-Science/Feast/ride-sharing-example.ipynb
Tested the Feast example notebook. 
Removed the unwanted pip install commands from previous version.
=> Feast tut update

Dockerfile
=> add model monitoring example folder in docker file

demos/fraud-detection/README.md, demos/fraud-detection/experiment.ipynb
This PR introduces two fixes to the Fraud Detection demo:
1. During the model deployment step in the KF pipeline, the system is unable to read the `USER` environment variable, leading to a failure. This PR addresses this issue by creating a new variable to hold the current user and pass it to the pipeline.
1. Currently, the model deployment step isn't isolated in the pipeline; it's combined with the logistic regression training step. This PR separates the model deployment process in a new pipeline step.
Closes #68
Checklist:
=> Improve the Fraud Detection demo

Data-Science/MLflow/bike-sharing-prediction.ipynb
=> change env var

Data-Science/MLflow/bike-sharing-prediction.ipynb, Data-Science/MLflow/kserve/kserve-minio-secret.yaml
=> fix object store secret name

Data-Science/Ray-Serve/check.py, Data-Science/Ray-Serve/ray_serving.ipynb, Data-Science/Ray-Serve/readme.md, Data-Science/Ray-Serve/snycheck.py
**The following demos are properly validated and enhanced, therefore, user can understand how RAY framework works on top of EZUA:** 
Maximising Online Inference: Exploring Ray Serve and Diverse Methodologies
1. A Deep Dive into Ray Serve with the Agile FastAPI Web Framework Approach.
2. Navigating Ray Serve through RayServeSyncHandle's Methodological Approach.
Reference: 
https://docs.ray.io/en/latest/serve/index.html
=> EZAF-3535 | Ray Serve | FastApi | RaySyncHandles

Data-Science/MLflow/bike-sharing-mlflow.ipynb
=> Fix trailing /n in bike sharing tutorial

Data-Analytics/Spark-GPU/README.md, Data-Analytics/Spark/DataProcessTransfer/README.md, Data-Analytics/Spark/DataTransfer/README.md
Updated the readme for spark oss and s3 connection as well as updated the spark gpu readme files.
Reference Jira:
- https://jira-pro.it.hpe.com:8443/browse/EZAF-4174
- https://jira-pro.it.hpe.com:8443/browse/EZAF-4162
=> Updated the readme files

install.sh
=> update image tag

install.sh
=> Update EZUA Tutorials Image

Makefile, demos/question-answering/dockerfiles/vectorstore/Dockerfile
Connect the repository with the internal CI/CD pipeline to automate the process of building and pushing the docker images to the public registry.
Checklist:
=> Connect the repository with the internal CI/CD pipeline

Data-Science/Ray/Hyperparameter/hyperparameter.py, Model-Monitoring/Airflow/README.md
=> Minior Fix

E2E-Demos/Investment-Banking/Airflow/spark_etl_new.yaml, E2E-Demos/Investment-Banking/Spark/spark_etl_new.yaml
=> Fixed S3 access key, secret key and endpoint

Makefile, install.sh
=> update ezua tutorial image tag

Makefile, install.sh
=> change makefile

Data-Science/Kubeflow-GPU/README.md
- Updated section Running Kubeflow Notebooks on GPU.
Closes [EZAF-3520](https://jira-pro.it.hpe.com:8443/browse/EZAF-3520)
Checklist:
=> EZAF-3520: Update kubeflow-gpu doc for fy23-q4

Data-Science/Kubeflow-GPU/README.md
- Updated section Running Kubeflow Notebooks on GPU.
Closes [EZAF-3520](https://jira-pro.it.hpe.com:8443/browse/EZAF-3520)
Checklist:
=> EZAF-3520: Update kubeflow-gpu doc for fy24-q1

Data-Science/Ray/Ray-CPU/Hyperparameter/README.md, Data-Science/Ray/Ray-CPU/Matrix_Multiplication/ray-matrix_multiplication-executor.ipynb
Fixed ray-matrix-multiplication example. 
Tested on EZUA 
Checklist:
=> fixed ray-matrix-multiplication-example

Model-Monitoring/Spark/Data_Validation_Spark.ipynb, Model-Monitoring/Spark/Whylogs_Profiling_Spark.ipynb
Created new whylogs image gcr.io/mapr-252711/spark-3.5.0:202405022330R with CVE fixes based on gcr.io/mapr-252711/spark-3.5.0:v3.5.0.3.4 
Verified it on apps cluster with spark + whylogs examples
=> Updated Whylogs image

Data-Engineering/Airflow/example_spark_pi_oss.yaml
=> Fixed Spark-pi-OSS example

Data-Science/MLflow/bike-sharing-prediction.ipynb
- Added new cell for PROFILE_NAMESPACE variable under PREDICTION section
Closes #...
Checklist:
=> add profile-namespace variable to bikesharing example

Data-Science/Ray/Ray-GPU/ray-gpu-executor.ipynb
**Jira**:https://jira-pro.it.hpe.com:8443/browse/EZAF-5850
**Issue:**
Tensorflow 2.15.1 not able to detect GPU 
https://github.com/tensorflow/tensorflow/issues/64881
[tensorflow not getting cuda drivers · Issue #70960 · tensorflow/tensorflow · GitHub](https://github.com/tensorflow/tensorflow/issues/70960)
**Fix:**
Overriding TF version through runtime environment. 
Checklist:
=> EZAF-5850 Updated Ray-GPU example

Data-Science/Kubeflow/MNIST-Digits-Recognition/mnist_katib_tf_kserve_example.ipynb
JIRA Ticket : https://jira-pro.it.hpe.com:8443/browse/EZAF-6016
Removed the extra comment.
- ...
Closes #...
Checklist:
=> EZAF-6016 Remove extra comment from MNIST example

Data-Science/Kubeflow/MNIST-Digits-Recognition/mnist_katib_tf_kserve_example.ipynb
In response to JIRA Ticket : https://jira-pro.it.hpe.com:8443/browse/EZAF-6037
- ...
Closes #...
Checklist:
=> EZAF-6037 Update the comment for Users in MNIST example

Data-Engineering/Airflow/example_ezaf_spark_csv_to_parquet_fts.yaml, Data-Engineering/Airflow/example_ezaf_spark_mnist.yaml
Jira: https://jira-pro.it.hpe.com:8443/browse/EZAF-6115
Fix: Added resource limit in FTS and MNIST example
=> EZAF-6115 Update Airflow example

Data-Engineering/Airflow/example_ezaf_spark_csv_to_parquet_fts.yaml, Data-Engineering/Airflow/example_ezaf_spark_mnist.yaml
jira :https://jira-pro.it.hpe.com:8443/browse/EZAF-6115
=> EZAF-6115 Airflow  example update 

Model-Monitoring/Spark/Data_Validation_Spark.ipynb, Model-Monitoring/Spark/Whylogs_Profiling_Spark.ipynb
https://jira-pro.it.hpe.com:8443/browse/EZAF-6107
https://jira-pro.it.hpe.com:8443/browse/EZAF-6230
https://github.hpe.com/hpe/ezaf/pull/3014
https://github.com/mapr/private-k8scompute-dockerfiles/pull/125
=> [EZAF-6107] Model monitoring for Spark applications is not working

Model-Monitoring/Airflow/airflow_whylog.py
=> Update whylogs example
